
// Code generated by go generate; DO NOT EDIT.
package main

type Expr interface{
    isExpr()
}


type Binary struct {
        Left Expr
        Right Expr
        Operator Token
}

type Grouping struct {
        Expression Expr
}

type Literal struct {
        Value interface{}
}

type Unary struct {
        Operator Token
        Right Expr
}

func (b Binary) isExpr() {}
func (g Grouping) isExpr() {}
func (l Literal) isExpr() {}
func (u Unary) isExpr() {}

